"""empty message

Revision ID: 4c76c6bf3a07
Revises: 
Create Date: 2024-10-29 11:38:56.677753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c76c6bf3a07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profil_photo', sa.LargeBinary(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=255), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anonymous_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=36), nullable=False),
    sa.Column('visit_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id')
    )
    op.create_table('subject_forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=255), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=254), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('profil_photo', sa.LargeBinary(), nullable=False),
    sa.Column('chemin_photo', sa.String(length=255), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('date_banned', sa.DateTime(), nullable=True),
    sa.Column('date_ban_end', sa.DateTime(), nullable=True),
    sa.Column('count_ban', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudo')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('embed_url', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('chat_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=30), nullable=False),
    sa.Column('request_content', sa.Text(), nullable=False),
    sa.Column('date_rdv', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heure', sa.Time(), nullable=False),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_choices', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_choice', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject_forum.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes_comment_subject',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.create_table('likes_comment_video',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_video.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.create_table('reply_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_content', sa.Text(), nullable=False),
    sa.Column('reply_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_content', sa.Text(), nullable=False),
    sa.Column('reply_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_video.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_video')
    op.drop_table('reply_subject')
    op.drop_table('likes_comment_video')
    op.drop_table('likes_comment_subject')
    op.drop_table('comment_video')
    op.drop_table('comment_subject')
    op.drop_table('chat_request')
    op.drop_table('video')
    op.drop_table('user')
    op.drop_table('subject_forum')
    op.drop_table('anonymous_visit')
    op.drop_table('admin')
    # ### end Alembic commands ###
